### ISSUE TITLE
centos repos are bad URLs and break this whole install

### ISSUE THREAD

**Issue by loquanet** [forbearing/k8s-ha-install#1]
dns can't resolve fails so install is jacked up.
ping mirrors.aliyuncs.com
ping mirrors.cloud.aliyuncs.com

ruined my servers and had to rebuild repos from scratch!
Change the script to backup existing repos and restore if install fails.

Still install doesn't work since etcd failed install, can't be installed since the repos were broken by your script.

**Comment by loquanet** [comment]
You need to note that timezone and dns is asian coded.
This isn't a honest and good code. There should be options and understand vm-tools will break a VM in working environments.

You need to make these options and not hard coded.

**Comment by forbearing** [comment]
many thanks 😁

I fixed it.
1. support timezone, but the default timezone is Asia/Shanghai, you can change it in k8s.env
2. backup yum repo to ${repo_name}.bak
3. disable open-vm-tools

**Comment by forbearing** [comment]
I'm feel sorry to heard that the script ruined your servers

**Comment by forbearing** [comment]
thanks your issue, and  I'm so sad to heard that the script ruined your server.

I fixed it.
1. support timezone, but the default timezone is Asia/Shanghai, you can change it in k8s.env
2. backup yum repo  to ${repo_name}.$(date +%Y%m%d%H%M)
3. disable open-vm-tools

**Comment by loquanet** [comment]
I had to comment out preparing step 1-4, and 6. Its best to just do the
minimum install only for k8s not for any other setup.

Skip repo,
I think skipping any yum repo adjustments would be best. Overriding repos
not knowing url restrictions or if the site mirror is working or not is
something to skip in your scripts.

Skip sshd,
Adjusting any sshd can break 3rd party SaaS or central login enterprise
management.

Option to skip all prepare or skip each step and what it does could be
helpful.


Skip docker cs,
Or allow to choose a local US or from a list of mirrors for docker install
Docker ce install mirror locations being in China isn't good either and a
private docker in China as well.

It still does not work and I'm working through why etcd isn't installing.

**Comment by forbearing** [comment]
Skip repo:
I only adjusted yum repo for "Asia/Shanghai" or "Asia/Chongqing", If it's not will keep the default yum repo.
You know, China has internet censorship, I need bypass balabala.


Skip sshd
this is a good idea, It is really not friendly to cloud vhost like AWS/GCP, etc.
It's necessary provide an option to skip stage prepare,
currently you can comment out stage one-three in setup.sh script
function main {
    #stage_prepare
    #stage_one
    #stage_two
    #stage_three
    #stage_four
    stage_five
}


Provide an option for stage one-three and skip docker cs will be coming later


etcd still does not work because of repeated generate etcd certificate
exec command "systemctl stop etcd; rm -rf /var/lib/etcd"  in all k8s master node(etcd node) and run stage_five again!

**Comment by loquanet** [comment]
The 3_install_docker is wrong and doesn't think about k8s rules:
- it assumes centos 7 and installs the wrong old package.
- And docker needs to match the k8e version you plan to install that is compatible with the apps you are going to use.
- I need v1.20 and docker v20.10 so your script would install and cause more work to uninstall
- Your private docker Registry mirror and insecure doesn't work in USA. 
1. Why do you use your own private docker for the setup? 
2. Why not give the option to insert our own or tell us to register if needed?

- Many conflicts with exsting containerd and deps. You assume docker isn't installed or older version conflicts. docker in full must be deleted for your script to install docker correctly.
- use dnf not yum...dnf is newer and superior.


function 1_install_docker {
    MSG2 "1. [`hostname`] Install docker"
	dnf remove  docker-ce docker-ce-cli containerd.io -y
    dnf install -y docker-ce-20.10.0-3.el8
	dnf install -y https://download.docker.com/linux/centos/8/x86_64/stable/Packages/docker-ce-cli-20.10.0-3.el8.x86_64.rpm
	dnf install -y https://download.docker.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.4.9-3.1.el8.x86_64.rpm  
    systemctl enable --now docker
	sudo usermod -aG docker $USER
	id $USER
	sudo systemctl disable firewalld

**Comment by loquanet** [comment]
New errors below failing install:

3. Setup haproxy
haproxy.cfg                                                        100%  840   152.4KB/s   00:00
Job for haproxy.service failed because the control process exited with error code.
See "systemctl status haproxy.service" and "journalctl -xe" for details.

4. Setup Keepalived
keepalived.conf_k8e-master.entworld.int                            100%  549   649.0KB/s   00:00
check_apiserver.sh                                                 100%  354    72.2KB/s   00:00
Job for haproxy.service failed because the control process exited with error code.
See "systemctl status haproxy.service" and "journalctl -xe" for details.

5. Generate certs for etcd
The connection to the server localhost:8080 was refused - did you specify the right host or port?

etcd hostname string: k8e-master.entworld.int,master6,master4,master5,10.0.11.230,10.250.13.16,10.250.13.14,10.250.13.15,127.0.0.1
scripts/4_stage_four.sh: line 197: cfssl: command not found
scripts/4_stage_four.sh: line 197: cfssl-json: command not found
scripts/4_stage_four.sh: line 198: cfssl: command not found
scripts/4_stage_four.sh: line 205: cfssl-json: command not found

6. Generate certs for Kubernetes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

kubernetes hostname string: k8e-master.entworld.int,master6,master4,master5,10.0.11.230,10.250.13.16,10.250.13.14,10.250.13.15,10.0.11.230,172.18.0.1,127.0.0.1,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.default.svc.cluster.local
scripts/4_stage_four.sh: line 252: cfssl: command not found
scripts/4_stage_four.sh: line 252: cfssl-json: command not found
scripts/4_stage_four.sh: line 253: cfssl: command not found
scripts/4_stage_four.sh: line 253: cfssl-json: command not found
scripts/4_stage_four.sh: line 255: cfssl: command not found
scripts/4_stage_four.sh: line 262: cfssl-json: command not found
scripts/4_stage_four.sh: line 264: cfssl: command not found
scripts/4_stage_four.sh: line 270: cfssl-json: command not found
scripts/4_stage_four.sh: line 289: cfssl: command not found
scripts/4_stage_four.sh: line 295: cfssl-json: command not found
error: could not stat certificate-authority file /etc/kubernetes/pki/ca.pem: stat /etc/kubernetes/pki/ca.pem: no such file or directory
error: could not stat client-certificate file /etc/kubernetes/pki/controller-manager.pem: stat /etc/kubernetes/pki/controller-manager.pem: no such file or directory
Context "system:kube-controller-manager@kubernetes" modified.
Switched to context "system:kube-controller-manager@kubernetes".
scripts/4_stage_four.sh: line 318: cfssl: command not found
scripts/4_stage_four.sh: line 324: cfssl-json: command not found
error: could not stat certificate-authority file /etc/kubernetes/pki/ca.pem: stat /etc/kubernetes/pki/ca.pem: no such file or directory
error: could not stat client-certificate file /etc/kubernetes/pki/scheduler.pem: stat /etc/kubernetes/pki/scheduler.pem: no such file or directory
Context "system:kube-scheduler@kubernetes" modified.
Switched to context "system:kube-scheduler@kubernetes".
scripts/4_stage_four.sh: line 348: cfssl: command not found
scripts/4_stage_four.sh: line 354: cfssl-json: command not found
error: could not stat certificate-authority file /etc/kubernetes/pki/ca.pem: stat /etc/kubernetes/pki/ca.pem: no such file or directory
error: could not stat client-certificate file /etc/kubernetes/pki/admin.pem: stat /etc/kubernetes/pki/admin.pem: no such file or directory
Context "kubernetes-admin@kubernetes" modified.
Switched to context "kubernetes-admin@kubernetes".
error: could not stat certificate-authority file /etc/kubernetes/pki/ca.pem: stat /etc/kubernetes/pki/ca.pem: no such file or directory
User "tls-bootstrap-token-user" set.
Context "tls-bootstrap-token-user@kubernetes" modified.
Switched to context "tls-bootstrap-token-user@kubernetes".
Generating RSA private key, 2048 bit long modulus (2 primes)
...............+++++
.....................................+++++
e is 65537 (0x010001)
writing RSA key

7. Copy etcd and k8s certs and config file
/etc/etcd/ssl/etcd-ca-key.pem: No such file or directory
/etc/etcd/ssl/etcd-ca.pem: No such file or directory
/etc/etcd/ssl/etcd-key.pem: No such file or directory
/etc/etcd/ssl/etcd.pem: No such file or directory
/etc/kubernetes/pki/ca.pem: No such file or directory
/etc/kubernetes/pki/ca-key.pem: No such file or directory
/etc/kubernetes/pki/front-proxy-ca.pem: No such file or directory
/etc/kubernetes/pki/front-proxy-ca-key.pem: No such file or directory
/etc/kubernetes/pki/admin.pem: No such file or directory
/etc/kubernetes/pki/admin-key.pem: No such file or directory
sa.key                                                             100% 1675   323.6KB/s   00:00
sa.pub                                                             100%  451   435.7KB/s   00:00
/etc/kubernetes/pki/apiserver.pem: No such file or directory
/etc/kubernetes/pki/apiserver-key.pem: No such file or directory
/etc/kubernetes/pki/controller-manager.pem: No such file or directory
/etc/kubernetes/pki/controller-manager-key.pem: No such file or directory
/etc/kubernetes/pki/scheduler.pem: No such file or directory
/etc/kubernetes/pki/scheduler-key.pem: No such file or directory
/etc/kubernetes/pki/front-proxy-client.pem: No such file or directory
/etc/kubernetes/pki/front-proxy-client-key.pem: No such file or directory
controller-manager.kubeconfig                                      100%  266   771.7KB/s   00:00
scheduler.kubeconfig                                               100%  239   484.3KB/s   00:00
bootstrap-kubelet.kubeconfig                                       100%  319   684.0KB/s   00:00
admin.kubeconfig                                                   100%  224   365.2KB/s   00:00
/etc/kubernetes/pki/ca.pem: No such file or directory
/etc/kubernetes/pki/front-proxy-ca.pem: No such file or directory
bootstrap-kubelet.kubeconfig                                       100%  319   285.5KB/s   00:00
/etc/kubernetes/pki/ca.pem: No such file or directory
/etc/kubernetes/pki/front-proxy-ca.pem: No such file or directory
bootstrap-kubelet.kubeconfig                                       100%  319   512.3KB/s   00:00
/etc/kubernetes/pki/ca.pem: No such file or directory
/etc/kubernetes/pki/front-proxy-ca.pem: No such file or directory
bootstrap-kubelet.kubeconfig                                       100%  319   427.9KB/s   00:00

8. Setup etcd

INITIAL_CLUSTER: k8e-master.entworld.int=https://10.0.11.230:2380
etcd.service                                                       100%  307   578.2KB/s   00:00
etcd.config.yaml_k8e-master.entworld.int                           100% 1384     2.5MB/s   00:00

9. Setup kube-apiserver
ETCD_SERVERS: https://10.0.11.230:2379 \
kube-apiserver.service_k8e-master.entworld.int                     100% 2047   825.4KB/s   00:00
Job for etcd.service failed because the control process exited with error code.
See "systemctl status etcd.service" and "journalctl -xe" for details.

10. Setup kube-controller-manager
kube-controller-manager.service                                    100% 1255     3.0MB/s   00:00

11. Setup kube-scheduler
kube-scheduler.service                                             100%  536     1.4MB/s   00:00

12. Setup K8S admin
mkdir: cannot create directory ‘/root/.kube’: File exists
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by loquanet** [comment]
cfssl is no longer supported in new versions.
https://github.com/cloudflare/cfssl/issues/774

**Comment by loquanet** [comment]
How did you get this "k8s-ha-install" to work with a generic server? You must have had go and the other alias and exports setup already. I don't see how this setup.sh would work at all yet.

- Seems go install is needed for commands cfssl and cfssljson
- There is no dash cfssl-json file 
- The command has to start with go, unless you create a bash alias for those two commands, eg. # go cfssl  

# install cfssl
		go get -u https://github.com/cloudflare/cfssl/cmd/cfssl/cfssl.go
		go get -u https://github.com/cloudflare/cfssl/blob/master/cmd/cfssljson/cfssljson.go
		cp cfss.go /usr/local
		cp cfssjson.go /usr/local
		cp cfssjson.go /usr/local/cfss-json.go

**Comment by forbearing** [comment]
my server is vmware vsphere virtual host,

in stage4, are you comment 1_copy_binary_package_and_create_dir?
1_copy_binary_package_and_create_dir function will copy binary file and create directory for k8s.

**Comment by loquanet** [comment]
Changed the code completely for install docker:

function 1_install_docker {
    MSG2 "1. [`hostname`] Install docker"
	# remove docker first to guarantee works
        rm -fr /etc/docker
	dnf remove -y docker-ce docker-ce-cli containerd.io
    # install docker-ce and deps
    dnf install -y docker-ce --nobest -y
    systemctl enable --now docker
	sudo usermod -aG docker $USER
	id $USER
	sudo systemctl disable firewalld
	systemctl start docker
}

**Comment by loquanet** [comment]
The setup is still failing if ran twice. I have to delete all files copied or the scripts add more lines to conf files and breaks the install.

You need to split up this setup.sh to 2 files. one for first run and one for adding a node after everything works. And add more verification that all services are running on all nodes and master.

**Comment by loquanet** [comment]
### **You changed the whole project code for scripts, setup, env, and repos without telling us.**

- And now very hard to restart to inject my working code from your errored code. I get errors on all stages from all nodes now. 
- 2 weeks of working with your old code and now have to debug on all nodes and fix instead of just 1 server all nodes that have the same errors executing on all.
- You should script to install on master and be certain it works then deploy to worker nodes.
### 
**So many errors in all stages now: how do you publish this and its code isn't working at all???**

### Error 

In centos/ install docker / config docker
registry - mirrors don't work they are your private mirrors and we don't have usernames or passwords or can DNS resolve this at all. 
insecure registry: same issue.


### Error because of china docker image cannot get to that file
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig"
Environment="KUBELET_SYSTEM_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_CONFIG_ARGS=--config=/etc/kubernetes/kubelet-conf.yaml **### --pod-infra-container-image=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.4.1"**

**Comment by loquanet** [comment]
### Error

Sep 04 20:29:47 k8e-master.entworld.int Keepalived_vrrp[708077]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 20:29:52 k8e-master.entworld.int Keepalived_vrrp[708199]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error

**Comment by loquanet** [comment]
### Error 1

function 5_generate_etcd_certs {
    MSG2 "5. Generate certs for etcd"

    # 如果 kubernetees 在部署成功，就不重新生成 etcd 证书
 **### >>>> this causes error when run kubectl get node ....nothing happens in command prompt
###  # **if kubectl get node; then return; fi****
    [[ ! -d ${K8S_PATH} ]] && rm -rf "${K8S_PATH}"; mkdir -p "${K8S_PATH}"
    [[ ! -d ${ETCD_CERT_PATH} ]] && rm -rf "${ETCD_CERT_PATH}"; mkdir -p "${ETCD_CERT_PATH}"




### Error 2


5. Generate certs for etcd
No resources found

### Error 2a

6. Generate certs for Kubernetes
No resources found

**Comment by loquanet** [comment]
### Error 3
cfssl-certinfo                                                                      100%   11MB  90.8MB/s   00:00
scp: /usr/local/bin//kube-apiserver: Text file busy
scp: /usr/local/bin//kube-controller-manager: Text file busy
scp: /usr/local/bin//kube-scheduler: Text file busy
scp: /usr/local/bin//kube-proxy: Text file busy
kubelet                                                                             100%  109MB 214.7MB/s   00:00
kubectl                                                                             100%   38MB 238.2MB/s   00:00
scp: /usr/local/bin//kube-proxy: Text file busy
kubelet                                                                             100%  109MB 226.9MB/s   00:00
kubectl                                                                             100%   38MB 230.0MB/s   00:00
scp: /usr/local/bin//kube-proxy: Text file busy
kubelet                                                                             100%  109MB 254.8MB/s   00:00
kubectl                                                                             100%   38MB 277.2MB/s   00:00
scp: /usr/local/bin//kube-proxy: Text file busy
kubelet                                                                             100%  109MB 258.7MB/s   00:00
kubectl

**Comment by loquanet** [comment]
### Error 4 


12. Setup K8S admin
mkdir: cannot create directory ‘/root/.kube’: File exists
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused
etcd-0               Healthy     {"health":"true"}

**Comment by loquanet** [comment]
### Error 5

12. Setup K8S admin
mkdir: cannot create directory ‘/root/.kube’: File exists
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                                                                                                                                                      ERROR
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection r                                                                                                                               efused
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection r                                                                                                                               efused
etcd-0               Healthy     {"health":"true"}                                                                                                                                                                                                   
secret/bootstrap-token-c8ad9c configured
clusterrolebinding.rbac.authorization.k8s.io/kubelet-bootstrap unchanged
clusterrolebinding.rbac.authorization.k8s.io/node-autoapprove-bootstrap unchanged
clusterrolebinding.rbac.authorization.k8s.io/node-autoapprove-certificate-rotation unchanged
clusterrole.rbac.authorization.k8s.io/system:kube-apiserver-to-kubelet unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:kube-apiserver unchanged


### Error 6
13. Setup kubelet
kubelet.service                                                                     100%  271   568.9KB/s   00:00
10-kubelet.conf                                                                     100%  781   897.3KB/s   00:00
kubelet-conf.yaml                                                                   100% 1853     1.7MB/s   00:00
A dependency job for kubelet.service failed. See 'journalctl -xe' for details.
kubelet.service                                                                     100%  271   322.2KB/s   00:00
10-kubelet.conf                                                                     100%  781     1.1MB/s   00:00
kubelet-conf.yaml                                                                   100% 1853     1.4MB/s   00:00
A dependency job for kubelet.service failed. See 'journalctl -xe' for details.
kubelet.service                                                                     100%  271   395.3KB/s   00:00
10-kubelet.conf                                                                     100%  781   978.7KB/s   00:00
kubelet-conf.yaml                                                                   100% 1853     1.3MB/s   00:00
A dependency job for kubelet.service failed. See 'journalctl -xe' for details.
kubelet.service                                                                     100%  271   279.1KB/s   00:00
10-kubelet.conf                                                                     100%  781     1.3MB/s   00:00
kubelet-conf.yaml                                                                   100% 1853     2.3MB/s   00:00
A dependency job for kubelet.service failed. See 'journalctl -xe' for details.

**Comment by loquanet** [comment]
### Error 

-- The result is failed.
Sep 04 22:52:51 k8e-master.entworld.int systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
Sep 04 22:52:51 k8e-master.entworld.int kube-proxy[940642]: I0904 22:52:51.682999  940642 proxier.go:1036] Not syncing ipvs rules until Services and Endpoints have been received from master
Sep 04 22:52:53 k8e-master.entworld.int Keepalived_vrrp[943039]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 22:52:58 k8e-master.entworld.int Keepalived_vrrp[943166]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 22:52:58 k8e-master.entworld.int kube-apiserver[938423]: E0904 22:52:58.049522  938423 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
Sep 04 22:53:03 k8e-master.entworld.int Keepalived_vrrp[943271]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 22:53:04 k8e-master.entworld.int kube-apiserver[938423]: E0904 22:53:04.536124  938423 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
Sep 04 22:53:04 k8e-master.entworld.int kube-apiserver[938423]: E0904 22:53:04.911383  938423 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
Sep 04 22:53:04 k8e-master.entworld.int kube-proxy[940642]: E0904 22:53:04.912292  940642 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Unauthorized
Sep 04 22:53:06 k8e-master.entworld.int kube-controller-manager[938773]: E0904 22:53:06.846927  938773 resource_quota_controller.go:409] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable>
Sep 04 22:53:08 k8e-master.entworld.int Keepalived_vrrp[943374]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 22:53:11 k8e-master.entworld.int kube-apiserver[938423]: I0904 22:53:11.323193  938423 client.go:360] parsed scheme: "passthrough"
Sep 04 22:53:11 k8e-master.entworld.int kube-apiserver[938423]: I0904 22:53:11.323268  938423 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.0.11.230:2379  <nil> 0 <nil>}] <nil> <nil>}
Sep 04 22:53:11 k8e-master.entworld.int kube-apiserver[938423]: I0904 22:53:11.323289  938423 clientconn.go:948] ClientConn switching balancer to "pick_first"
Sep 04 22:53:11 k8e-master.entworld.int kube-apiserver[938423]: I0904 22:53:11.323613  938423 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0066471a0, {CONNECTING <nil>}
Sep 04 22:53:11 k8e-master.entworld.int kube-apiserver[938423]: I0904 22:53:11.331912  938423 balancer_conn_wrappers.go:78] pickfirstBalancer: HandleSubConnStateChange: 0xc0066471a0, {READY <nil>}
Sep 04 22:53:11 k8e-master.entworld.int kube-apiserver[938423]: I0904 22:53:11.333111  938423 controlbuf.go:508] transport: loopyWriter.run returning. connection error: desc = "transport is closing"
Sep 04 22:53:12 k8e-master.entworld.int kube-controller-manager[938773]: I0904 22:53:12.446278  938773 request.go:655] Throttling request took 1.047446524s, request: GET:https://10.0.11.230:8443/apis/authentication.k8s.io/v1beta1?timeout=32s
Sep 04 22:53:13 k8e-master.entworld.int Keepalived_vrrp[943494]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 22:53:13 k8e-master.entworld.int kube-controller-manager[938773]: W0904 22:53:13.298611  938773 garbagecollector.go:703] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
Sep 04 22:53:16 k8e-master.entworld.int kube-apiserver[938423]: E0904 22:53:16.880229  938423 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
Sep 04 22:53:18 k8e-master.entworld.int Keepalived_vrrp[943598]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 22:53:18 k8e-master.entworld.int kube-apiserver[938423]: E0904 22:53:18.365995  938423 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
Sep 04 22:53:19 k8e-master.entworld.int kube-scheduler[939123]: I0904 22:53:19.230533  939123 factory.go:319] "Unable to schedule pod; no nodes are registered to the cluster; waiting" pod="kube-system/calico-kube-controllers-5c66c76d4f-5w5bs"
Sep 04 22:53:19 k8e-master.entworld.int kube-scheduler[939123]: I0904 22:53:19.230730  939123 factory.go:319] "Unable to schedule pod; no nodes are registered to the cluster; waiting" pod="kube-system/coredns-867bfd96bd-978f5"
Sep 04 22:53:19 k8e-master.entworld.int kube-scheduler[939123]: I0904 22:53:19.230866  939123 factory.go:319] "Unable to schedule pod; no nodes are registered to the cluster; waiting" pod="kube-system/metrics-server-7956dbcff9-gwn28"


### Error 
Your code is breaking docker config as well.


-- Unit docker.service has finished shutting down.
Sep 04 22:54:48 k8e-master.entworld.int systemd[1]: docker.service: Start request repeated too quickly.
Sep 04 22:54:48 k8e-master.entworld.int systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 04 22:54:48 k8e-master.entworld.int systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit docker.service has failed.
--
-- The result is failed.
Sep 04 22:54:48 k8e-master.entworld.int systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
Sep 04 22:54:49 k8e-master.entworld.int kube-apiserver[938423]: E0904 22:54:49.579253  938423 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
Sep 04 22:54:49 k8e-master.entworld.int kube-controller-manager[938773]: I0904 22:54:49.955995  938773 request.go:655] Throttling request took 1.047635004s, request: GET:https://10.0.11.230:8443/apis/authentication.k8s.io/v1?timeout=32s
Sep 04 22:54:50 k8e-master.entworld.int kube-controller-manager[938773]: W0904 22:54:50.808663  938773 garbagecollector.go:703] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
Sep 04 22:54:51 k8e-master.entworld.int kube-proxy[940642]: I0904 22:54:51.684302  940642 proxier.go:1036] Not syncing ipvs rules until Services and Endpoints have been received from master
Sep 04 22:54:53 k8e-master.entworld.int Keepalived_vrrp[945776]: Error exec-ing command '/etc/keepalived/check_apiserver.sh', error 8: Exec format error
Sep 04 22:54:53 k8e-master.entworld.int kube-apiserver[938423]: E0904 22:54:53.792464  938423 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]
Sep 04 22:54:53 k8e-master.entworld.int kube-proxy[940642]: E0904 22:54:53.793058  940642 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Unauthorized

**Comment by loquanet** [comment]
> my server is vmware vsphere virtual host,
> 
> in stage4, are you comment 1_copy_binary_package_and_create_dir?
> 1_copy_binary_package_and_create_dir function will copy binary file and create directory for k8s.

deploy on centos 8 vm and you will see my issues is many errors
